### ISSUE TITLE
executing after_transaction in another model transaction

### ISSUE THREAD

**Issue by sevaorlov** [dtaniwaki/activerecord-after-transaction#2]
Hi, if you execute `after_transaction` in not self model transaction, then the block won't be called. I don't know, maybe due to the bug, but `self.class.connection.open_transactions` returns number of open ActiveRecord transactions regardless of the class. If we are in another model transaction, then self model `after_commit` callback won't be triggered if self is not in AR transaction records to call after commit hooks.

**Comment by sevaorlov** [comment]
One solution is to add self to AR records to call after commit hooks:
`ActiveRecord::Base.connection.add_transaction_record self`

**Comment by dtaniwaki** [comment]
Thanks for your suggestion! I'll look into the issue.

**Comment by sevaorlov** [comment]
I'm using Rails 3.2.18, maybe the problem is fixed in later versions, I didn't check.

**Comment by dtaniwaki** [comment]
Does this solve the issue?
https://github.com/dtaniwaki/activerecord-after-transaction/pull/3

**Comment by sevaorlov** [comment]
I didn't try, but it should fix the problem
